# ------------- Config ----------------
AVARAGE_EXTRA_MATERIAL:     None
MAX_EXTRA_MATERIAL:         0.01
MAX_AREA_BETWEEN:           None
MIN_AREA_BETWEEN:           None
AVARAGE_AREA_BETWEEN:       None
# -------------------------------------